---
- name: install SSL key
  copy: >-
    owner=root
    group=root
    mode=400
    src={{pki_key}}
    dest=/etc/pki/tls/private/{{pki_key_file}}

- name: install SSL certificate
  copy: >-
    owner=root
    group=root
    mode=400
    src={{pki_cert}}
    dest=/etc/pki/tls/certs/{{pki_cert_file}}

- name: install root CA certificate
  copy: >-
    owner=root
    group=root
    mode=400
    src={{pki_ca_cert}}
    dest=/etc/pki/ca-trust/source/anchors/{{pki_ca_file}}
  register: cacertinstalled

- name: update CA trust...
  command: 'update-ca-trust extract'
  when: cacertinstalled.changed
  